/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal project workflows.
// It is committed here so TypeScript can resolve Next types from phase 1.
