modLoader="javafml"
loaderVersion="[64,)"
license="MIT"

[[mods]]
modId="simple_ruby_mod"
version="1.0.0"
displayName="Simple Ruby Mod"
logoFile="icon.png"
authors="Johna"
description='''A tiny Forge starter mod that adds a ruby item.'''

[[dependencies.simple_ruby_mod]]
    modId="forge"
    mandatory=true
    versionRange="[64,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simple_ruby_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.2,26.2,)"
    ordering="NONE"
    side="BOTH"
